export { Button } from './Button/Button';
export { StatsTab } from './StatsTab/StatsTab';
export { SecondaryTitle } from './SecondaryTitle/SecondaryTitle';
export { Title } from './Title/Title';
export { Header } from './Header/Header';
export { Footer } from './Footer/Footer';
export { LeftMenu } from './LeftMenu/LeftMenu';
export { Slide } from './Slide/Slide';
export { InfoSlide } from './InfoSlide/InfoSlide';
